### ISSUE TITLE
关于内存泄漏检测的疑问

### ISSUE THREAD

**Issue by opensource-weibiao** [xuexiangjys/TemplateAppProject#10]
我去掉了x-library.gradle中的
if (configuration.name == "debugImplementation") {
        //内存泄漏监测leak
        configuration.dependencies.add(getProject().dependencies.create('com.squareup.leakcanary:leakcanary-android:1.6.3'))
    }
    if (configuration.name == "releaseImplementation") {
        //内存泄漏监测leak
        configuration.dependencies.add(getProject().dependencies.create('com.squareup.leakcanary:leakcanary-android-no-op:1.6.3'))
    }
    if (configuration.name == "testImplementation") {
        //内存泄漏监测leak
        configuration.dependencies.add(getProject().dependencies.create('com.squareup.leakcanary:leakcanary-android-no-op:1.6.3'))
    }
这三段，发现运行闪退。 转而去修改BuildConfig中的debug为false，发现还是去不掉这个内存检测捆绑安装的Leaks，并且会一直推送消息。 老哥你可以直接在文档声明一下怎么去掉这个头疼的东西...

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/XPage#222application%E4%B8%AD%E5%8A%A8%E6%80%81%E6%B3%A8%E5%86%8C%E6%8E%A8%E8%8D%90
