### ISSUE TITLE
使用openNewPage方法调用fragment时不能初始化

### ISSUE THREAD

**Issue by chiyuhao** [xuexiangjys/TemplateAppProject#11]
我在一个fragment中对图片进行了处理并保存到服务器，之后调用openNewPage方法调用另一个fragment从服务器上获取图片，加载图片的方法写在了initViews里。但是发现这个显示图片的fragment并没有更新为新图片

**Comment by xuexiangjys** [comment]
这个和initViews有什么关系?有没有走打个日志就不清楚了.
你这种情况,十有八九是你用的图片加载库存在内存缓存,只要图片的url不变,不管你怎么编辑保持是不可能有任何变化的.

**Comment by chiyuhao** [comment]
你好，我ImageLoader的缓存策略是DiskCacheStrategyEnum.NONE， 然后还重载了setUserVisibleHint来让每次切换fragment的时候图片重新加载，但是还是不能显示出最新的图片。然后使用XUI那个项目的代码在图片-图片加载策略那个demo中图片的显示就会随着图的更新而更新，所以我在想是为什么。

**Comment by xuexiangjys** [comment]
内存缓存,懂?你那个是磁盘缓存,你还是自己好好看看吧
