### ISSUE TITLE
MaterialSpinner app release后无法使用

### ISSUE THREAD

**Issue by yesyeey** [xuexiangjys/TemplateAppProject#13]
MaterialSpinner app release后无法使用，debug可以使用，release取消混淆后也可以使用，请问如果使用混淆，该怎么配置呢

**Comment by xuexiangjys** [comment]
第一:MaterialSpinner是XUI的内容,你貌似提错地方了吧
第二:MaterialSpinner是不需要混淆配置的,你不能用总得贴点证据吧,你是想让我盲猜吗?
