### ISSUE TITLE
本机没有NDK 20.0版本，但指定NDK21.0 版后，出现一堆异常

### ISSUE THREAD

**Issue by blueflagbj** [xuexiangjys/TemplateAppProject#14]
本机没有指定NDK的版本，指定NDK 21.0.6113669 后，就一堆问题了！
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669

比如：Gradle sync failed: Could not get unknown property 'versions' for object of type ... 这类的，应该是兼容性的问题，但是直接clone XUI的APP倒可以直接编译

**Comment by xuexiangjys** [comment]
XUI使用的gradle是低版本，该项目使用的是高版本，没有你就升级版本啊
