### ISSUE TITLE
如何关闭模板项目编译产生的txt文件

### ISSUE THREAD

**Issue by volov157** [xuexiangjys/TemplateAppProject#15]
你好，请问我下载了模板项目，然后修改包名进入开发环节，在项目编译的时候会在根目录产生ajcore.*********.txt的文件，请问在哪里可以设置关闭？
![image](https://user-images.githubusercontent.com/15773474/89598153-ae554180-d88e-11ea-85dc-24f1cdd5efba.png)

**Comment by xuexiangjys** [comment]
你这是xaop库出现问题了,请参照文档配置或者降低gradle的版本
