### ISSUE TITLE
能添加一个通过文字生成头像的功能吗

### ISSUE THREAD

**Issue by xiaheshun** [xuexiangjys/TemplateAppProject#16]
类似于钉钉的那种默认有个名字的首字母或者姓来生成圆形或者方形的头像

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/XUI/blob/dev%2F1.1.6/xui_lib/src/main/java/com/xuexiang/xui/utils/DrawableUtils.java#L314
