### ISSUE TITLE
使用这个模版工程Xhttp请求网络时,服务器相应格式是正确的 但是回调走到了onerror 打印的内容是返回体的msg内容

### ISSUE THREAD

**Issue by Haowensheng** [xuexiangjys/TemplateAppProject#28]
这个是url http://192.168.101.195:8081/test?name=%E6%9D%83%E9%99%90%E6%B5%8B%E8%AF%95 
这个是输出的日志
I/[XHttp]: 	body:{"msg":"操作成功","code":200,"data":[{"name":"权限测试","id":1},{"name":"权限测试","id":2},{"name":"权限测试","id":3},{"name":"权限测试","id":4},{"name":"权限测试","id":5}]}
    <-- END HTTP
E/[XHttp]: --> Subscriber is onError
    --> e instanceof ApiException, message:操作成功

**Comment by xuexiangjys** [comment]
code = 0 代表成功,知道嘛
