### ISSUE TITLE
使用 xhttp 报类型转换错误 

### ISSUE THREAD

**Issue by ifnk** [xuexiangjys/TemplateAppProject#29]
按照 例子来写的 

CustomRequest request = XHttp.custom().cacheMode(CacheMode.FIRST_CACHE).cacheTime(TimeConstants.DAY).cacheKey("dudu");
request.apiCall(request.create(ApiService.IGetService.class).staffLogin("9527"), new TipCallBack<ApiResult<String>>() {
	@Override
	public void onSuccess(ApiResult<String> response) throws Throwable {
		XToastUtils.info("haha");

	}
});

api service 里面 是 这样的 
/**
 * 员工登录
 */
@GET("api/user/login")
Observable<ApiResult<String>> staffLogin(@Query("staffNo") String staffNo );

swagger 里面 可以 请求 成功 数据格式 是 
// http://localhost:5000/api/user/login?staffNo=9527

{
  "code": 0,
  "msg": "haha",
  "data": "dudu"
}

不知道是哪里出问题了 ……

**Comment by xuexiangjys** [comment]
报错日志贴一下...

**Comment by ifnk** [comment]
> 报错日志贴一下...

作者 我 明白 啦 ！ 我去看了 xhttp 的 说明 就解决了 ，这个是 new TipCallBack<String>() ,而不是 new TipCallBack<ApiResult<String>>
