### ISSUE TITLE
linux 下运行项目报错

### ISSUE THREAD

**Issue by ifnk** [xuexiangjys/TemplateAppProject#30]
我没有改项目名字跑的项目 

error 1 : Type com.xuexiang.xrouter.core.AutoWiredServiceImpl is defined multiple times: /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/124df5ace20db07e11dcf5c622e9251a51b6b4c6096e54d8d6c7f86c59555c48_1.jar:classes.dex, /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/f647141e8c50057b245b8215de958c085f490885dfd5d5c37587cc79b067bd40_1.jar:classes.dex

error2 : Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete

error3 : Caused by: com.android.tools.r8.utils.b: Error: /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/124df5ace20db07e11dcf5c622e9251a51b6b4c6096e54d8d6c7f86c59555c48_1.jar:classes.dex, Type com.xuexiang.xrouter.core.AutoWiredServiceImpl is defined multiple times: /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/124df5ace20db07e11dcf5c622e9251a51b6b4c6096e54d8d6c7f86c59555c48_1.jar:classes.dex, /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/f647141e8c50057b245b8215de958c085f490885dfd5d5c37587cc79b067bd40_1.jar:classes.dex

error4: Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Type com.xuexiang.xrouter.core.AutoWiredServiceImpl is defined multiple times: /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/124df5ace20db07e11dcf5c622e9251a51b6b4c6096e54d8d6c7f86c59555c48_1.jar:classes.dex, /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/f647141e8c50057b245b8215de958c085f490885dfd5d5c37587cc79b067bd40_1.jar:classes.dex
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

error5: Error: /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/124df5ace20db07e11dcf5c622e9251a51b6b4c6096e54d8d6c7f86c59555c48_1.jar:classes.dex, Type com.xuexiang.xrouter.core.AutoWiredServiceImpl is defined multiple times: /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/124df5ace20db07e11dcf5c622e9251a51b6b4c6096e54d8d6c7f86c59555c48_1.jar:classes.dex, /home/ifnk/AndroidStudioProjects/TemplateAppProject/app/build/intermediates/mixed_scope_dex_archive/debug/out/f647141e8c50057b245b8215de958c085f490885dfd5d5c37587cc79b067bd40_1.jar:classes.dex

其中 error2 我看了下 说是 我 java 版本 太高 ，但是 

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

我java 版本 就是 1.8没有改过

**Comment by xuexiangjys** [comment]
和java 1.8没有任何关系
