### ISSUE TITLE
TemplateAppProject中openPageForResult使用异常，该什么解决呢？

### ISSUE THREAD

**Issue by smapie** [xuexiangjys/TemplateAppProject#34]
下载好最新的TemplateAppProject后，将ProfileFragment中的openNewPage(AboutFragment.class);改为Bundle bundle=new Bundle(); openPageForResult(AboutFragment.class,bundle,100);，运行报错，
No view found for id 0x7f0900ea (com.xuexiang.templateproject:id/fragment_container) for fragment AboutFragment
我使用xpage的源码测试，里面的xpagedemo使用openPageForResult却没报错，是不是这个template集成了比较多的包后冲突了。这个我测试了好几个版本的templateappproject都是这样的问题，我调试了CorePageManager里面是有这个view的啊，为什么还提示找不到呢？

**Comment by xuexiangjys** [comment]
拜托，openNewPage能直接换成openPageForResult嘛？没看到有个New吗？
