### ISSUE TITLE
选择照片时对预览的大照片选择无效

### ISSUE THREAD

**Issue by myie9** [xuexiangjys/TemplateAppProject#4]
我把xuidemo里普通拍照的代码移植到您的这个TemplateAppProject工程中,
点击拍照, 再点击左下角的选择照片, 
然后点击某一个照片使其全屏预览, 点击右上角的勾选中, 
界面显示被选择了, 点击完成按钮,
界面回到很多个图片的界面后, 
但是那个图片并没有被选中.

我的有问题的apk:
http://sj.myie9.com/tmp/pick-pic.apk
点击 戴口罩自拍按钮

但是同一个手机中的xuidemo是正常的.

我的代码如下:
https://github.com/myie9/myietemplate/tree/%E9%A2%84%E8%A7%88%E7%85%A7%E7%89%87%E9%80%89%E6%8B%A9%E6%97%A0%E6%95%88-%E5%88%86%E6%94%AF

**Comment by xuexiangjys** [comment]
我直接拉下来代码运行了一下,没有你说的情况,考虑是打包出了问题

**Comment by myie9** [comment]
build variable设置成debug是正常的, 设置成release就会出现这个问题

**Comment by myie9** [comment]
> 我直接拉下来代码运行了一下,没有你说的情况,考虑是打包出了问题

build variable设置成debug是正常的, 设置成release就会出现这个问题

**Comment by xuexiangjys** [comment]
加一下混淆配置:

```
-keep class com.luck.picture.lib.** { *; }
```

**Comment by myie9** [comment]
> 加一下混淆配置:
> 
> ```
> -keep class com.luck.picture.lib.** { *; }
> ```

解决了.  非常感谢.  已对您项目微信赞助了100元, 备注用户名myie9

**Comment by xuexiangjys** [comment]
> > 加一下混淆配置:
> > ```
> > -keep class com.luck.picture.lib.** { *; }
> > ```
> 
> 解决了. 非常感谢. 已对您项目微信赞助了100元, 备注用户名myie9

捐赠名单已加上,感谢你的支持

**Comment by myie9** [comment]
客气.
