### ISSUE TITLE
请问位置定位和修改配置权限

### ISSUE THREAD

**Issue by myie9** [xuexiangjys/TemplateAppProject#5]
因为给市场提交时要求写明用到的权限是做什么用的,
可否说明一下这2个权限是用于什么功能的:位置定位和修改配置权限

另外,  我可否移除这2个权限,请问怎么搞

**Comment by xuexiangjys** [comment]
那是友盟统计sdk里携带的权限

**Comment by xuexiangjys** [comment]
还有就是`com.github.xuexiangjys.XUtil:xutil-core:1.1.6`库也会有

**Comment by myie9** [comment]
好.谢谢

**Comment by myie9** [comment]
> 还有就是`com.github.xuexiangjys.XUtil:xutil-core:1.1.6`库也会有

请问 修改配置权限 是什么功能修改了什么配置,  以便我给市场提交时写明.

**Comment by xuexiangjys** [comment]
> > 还有就是`com.github.xuexiangjys.XUtil:xutil-core:1.1.6`库也会有
> 
> 请问 修改配置权限 是什么功能修改了什么配置, 以便我给市场提交时写明.

用于获取和修改系统屏幕亮度的工具类用到的

**Comment by myie9** [comment]
谢谢
