### ISSUE TITLE
建议增加隐私及用户协调弹出页

### ISSUE THREAD

**Issue by myie9** [xuexiangjys/TemplateAppProject#6]
因为提交给华为等市场时，要求第一次打开app时得要有协议及隐私提醒，建议增加一个。
用对话框怎么在文字中增加一个协议的网址跳转，然后用app内置的webview打开？

我想还有一个方案就是在userguid里增加协议及隐私查看按钮

**Comment by xuexiangjys** [comment]
已经加好了:
fce0176fc5389f3c8fab0e383bfdd212dcc50aa7

**Comment by myie9** [comment]
谢谢，好快
