### ISSUE TITLE
里面的Glide有读取联系人权限，如何禁止

### ISSUE THREAD

**Issue by myie9** [xuexiangjys/TemplateAppProject#9]
Glide
框架
工具
多媒体
https://github.com/bumptech/glide
读取联系人
(2)
高敏
仅sdk
冗余权限
读取外置存储卡
(2)
高敏
写入外部存储卡
(2)
高敏

**Comment by xuexiangjys** [comment]
在manifest中使用`tools:node="remove"`进行去除.例如下面是去除读取联系人的权限.自己举一反三处理
```

<uses-permission
        android:name="android.permission.READ_CONTACTS"
        tools:node="remove" />
```
